In [1]:
import numpy as np
import pandas as pd

Question - 1 : Which pandas version are you using?

In [ ]:
pd.__version__

'3.0.5'

Getting the Data

In [4]:
df=pd.read_csv(r"C:\Users\hp\Downloads\car_fuel_efficiency_2026.csv")

In [6]:
df.sample(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
5553,1990,Asia,Gasoline,All-wheel drive,5,2310,6,274.0,4500,17.6,26.9
7062,1991,USA,Gasoline,Front-wheel drive,2,2700,7,312.0,4710,19.7,24.8
5587,1989,USA,Gasoline,All-wheel drive,3,2080,6,230.0,4290,20.3,26.4
6110,2001,Europe,Diesel,Front-wheel drive,3,2500,6,287.0,4290,16.7,29.7
6657,2003,Asia,Diesel,All-wheel drive,3,2460,6,282.0,4790,19.2,28.7

Question - 2 : How many records are in the dataset?

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

In [8]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

Question - 3 : How many fuel types are presented in the dataset?

In [ ]:
fuel_type_list=df['fuel_type'].unique()
print("Number of fuel types presented in the dataset are : ", len(fuel_type_list))

Number of fuel types presented in the dataset are :  3

Question - 4 : How many columns in the dataset have missing values?

In [ ]:
missing_cols=df.isna().sum()
num_missing_cols=(missing_cols>0).sum()
print("Number of missing columns in the dataset are : ", num_missing_cols)

Number of missing columns in the dataset are :  2

Question - 5 : What's the maximum fuel efficiency of cars from Asia?

In [22]:
fuel_eff_of_asian_cars=df[df['origin']=='Asia'].fuel_efficiency_mpg
print("Maximum fuel efficiency among asian cars is : ",max(fuel_eff_of_asian_cars))

Maximum fuel efficiency among asian cars is :  41.2

Question - 6 : Median value of horsepower                                       
            1. Find the median value of the horsepower column in the dataset.                                       
            2. Next, calculate the most frequent value of the same horsepower column.                                       
            3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.                                       
            4. Now, calculate the median value of horsepower once again.                                        
            Has it changed?

In [27]:
horsepower_median=df['horsepower'].median()
print("Horsepower median before filling : ", horsepower_median)

most_freq_horsepower=df['horsepower'].mode()[0]
df['horsepower'].fillna(most_freq_horsepower)
print("Missing values of horsepower are filled with most frequent value which is : ", most_freq_horsepower)

horsepower_median_new=df['horsepower'].median()
print("Horsepower midian after filling : ", horsepower_median_new)

Horsepower median before filling :  254.0
Missing values of horsepower are filled with most frequent value which is :  252.0
Horsepower midian after filling :  254.0

Question - 7 : Sum of weights                                       
1. Select all the cars from Asia                                        
2. Select only columns vehicle_weight and model_year                                        
3. Select the first 7 values                                        
4. Get the underlying NumPy array. Let's call it X.                                     
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.                                                         
6. Invert XTX.                                      
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].                                      
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.                

What's the sum of all the elements of the result?

In [32]:
asian_cars=df[df['origin']=='Asia'][['vehicle_weight','model_year']].head(7)
asian_cars

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [37]:
X=np.array(asian_cars)
XTX=np.dot(X.T, X)
inverse_XTX=np.linalg.inv(XTX)
y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

w=inverse_XTX.dot(X.T).dot(y)

print("Sum of all the elements of the result w : ", np.sum(w))

Sum of all the elements of the result w :  0.36919696904925486